/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [CalibrationSubTypeViewID]
      ,[CalibrationSubTypeId]
      ,[EnabledDrag]
      ,[EnabledDelete]
      ,[EnabledDuplicate]
      ,[EnabledHeader]
      ,[EnabledSelect]
      ,[EnabledNew]
      ,[PageSize]
      ,[CSSRow]
      ,[CSSRowSeparator]
      ,[EnableButtonBar]
      ,[ColButtonActionCSS]
      ,[ColActionCSS]
      ,[AlingActionCSS]
      ,[ActionBeginRow]
      ,[Key]
      ,[NoDataMessage]
      ,[CSSGrid]
      ,[SortField]
      ,[BlockIfInvalid]
      ,[FilterField]
      ,[FilterValue]
      ,[ShowHeader]
      ,[CSSForm]
      ,[CSSRowHeader]
      ,[IsVisible]
      ,[SaveButton]
      ,[CloseButton]
      ,[Style]
      ,[Component]
      ,[IsCollection]
      ,[UseResult]
      ,[ShowCardButton]
      ,[EnableEdit]
      ,[ColFormActionCSS]
      ,[IsRowView]
      ,[NewButtonTitle]
      ,[NewButtonCSS]
      ,[EnableSelect2]
      ,[SelectTitle]
      ,[Select2Title]
      ,[HasDelete]
      ,[HasNewButton]
  FROM [dbo].[CalibrationSubTypeView]
  where CalibrationSubTypeId=1687601224

  update [dbo].[CalibrationSubTypeView] set EnabledDelete=0, EnabledHeader=0, CSSGrid='CSSGridPanel'
  where CalibrationSubTypeId=1687601224


  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [CalibrationSubTypeViewID]
      ,[CalibrationSubTypeId]
      ,[EnabledDrag]
      ,[EnabledDelete]
      ,[EnabledDuplicate]
      ,[EnabledHeader]
      ,[EnabledSelect]
      ,[EnabledNew]
      ,[PageSize]
      ,[CSSRow]
      ,[CSSRowSeparator]
      ,[EnableButtonBar]
      ,[ColButtonActionCSS]
      ,[ColActionCSS]
      ,[AlingActionCSS]
      ,[ActionBeginRow]
      ,[Key]
      ,[NoDataMessage]
      ,[CSSGrid]
      ,[SortField]
      ,[BlockIfInvalid]
      ,[FilterField]
      ,[FilterValue]
      ,[ShowHeader]
      ,[CSSForm]
      ,[CSSRowHeader]
      ,[IsVisible]
      ,[SaveButton]
      ,[CloseButton]
      ,[Style]
      ,[Component]
      ,[IsCollection]
      ,[UseResult]
      ,[ShowCardButton]
      ,[EnableEdit]
      ,[ColFormActionCSS]
      ,[IsRowView]
      ,[NewButtonTitle]
      ,[NewButtonCSS]
      ,[EnableSelect2]
      ,[SelectTitle]
      ,[Select2Title]
      ,[HasDelete]
      ,[HasNewButton]
  FROM [dbo].[CalibrationSubTypeView]
  where CalibrationSubTypeId=28