
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Helpers.Models;
//
//    var csvValidation = CsvValidation.FromJson(jsonString);
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Helpers.Models
{
   
    public partial class CsvValidation
    {
        [JsonProperty("rowSeperator")]
        public string RowSeperator { get; set; }

        [JsonProperty("columnSeperator")]
        public string ColumnSeperator { get; set; }

        [JsonProperty("hasHeaderRow")]
        public bool HasHeaderRow { get; set; }

        [JsonProperty("columns")]
        public Dictionary<string, Column> Columns { get; set; }


        [JsonProperty("exampleUrl")]
        public string ExampleUrl { get; set; }

    }

    public partial class Column
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("isRequired", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsRequired { get; set; }

        [JsonProperty("unique", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Unique { get; set; }

        [JsonProperty("pattern", NullValueHandling = NullValueHandling.Ignore)]
        public string Pattern { get; set; }

        [JsonProperty("maxLength", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? MaxLength { get; set; }

        [JsonProperty("isNumeric", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsNumeric { get; set; }

        [JsonProperty("isOnlyRead", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsOnlyRead { get; set; }

        [JsonProperty("formula", NullValueHandling = NullValueHandling.Ignore)]
        public string Formula { get; set; }

        [JsonProperty("defaultValue", NullValueHandling = NullValueHandling.Ignore)]
        public string DefaultValue { get; set; }

        [JsonProperty("selectOptions", NullValueHandling = NullValueHandling.Ignore)]
        public string SelectOptions { get; set; }

        [JsonProperty("isBoolean", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsBoolean { get; set; }

        [JsonProperty("isReportView", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsReportView { get; set; }

        [JsonProperty("isHeader", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsHeader { get; set; }

        [JsonProperty("formulaClass", NullValueHandling = NullValueHandling.Ignore)]
        public string FormulaClass { get; set; }

    }

    public partial class CsvValidation
    {
        public static CsvValidation FromJson(string json) => JsonConvert.DeserializeObject<CsvValidation>(json, Helpers.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CsvValidation self) => JsonConvert.SerializeObject(self, Helpers.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
