CREATE TABLE [dbo].[ForceResult] (
    [SequenceID]                 INT            NOT NULL,
    [CalibrationSubTypeId]       INT            NOT NULL,
    [WorkOrderDetailId]          INT            NOT NULL,
    [FS]                         FLOAT (53)     NOT NULL,
    [Equipmet]                   INT            NOT NULL,
    [Nominal]                    FLOAT (53)     NOT NULL,
    [RUN1]                       FLOAT (53)     NOT NULL,
    [RUN2]                       FLOAT (53)     NOT NULL,
    [RUN3]                       FLOAT (53)     NOT NULL,
    [RUN4]                       FLOAT (53)     NOT NULL,
    [Error]                      FLOAT (53)     NOT NULL,
    [ErrorPer]                   FLOAT (53)     NOT NULL,
    [Uncertanty]                 FLOAT (53)     NOT NULL,
    [RelativeIndicationError]    FLOAT (53)     NOT NULL,
    [RelativeRepeatabilityError] FLOAT (53)     NOT NULL,
    [Class]                      NVARCHAR (MAX) NULL,
    [Resolution]                 FLOAT (53)     NOT NULL,
    [DecimalNumber]              INT            NOT NULL,
    [IncludeASTM]                FLOAT (53)     NOT NULL,
    [ErrorRun1]                  FLOAT (53)     NOT NULL,
    [ErrorRun2]                  FLOAT (53)     NOT NULL,
    [ErrorRun3]                  FLOAT (53)     NOT NULL,
    [ErrorRun4]                  FLOAT (53)     NOT NULL,
    [RelativeIndicationErrorR1]  FLOAT (53)     NOT NULL,
    [RelativeIndicationErrorR2]  FLOAT (53)     NOT NULL,
    [RelativeIndicationErrorR3]  FLOAT (53)     NOT NULL,
    [RelativeIndicationErrorR4]  FLOAT (53)     NOT NULL,
    [ZeroReturn]                 FLOAT (53)     NOT NULL,
    [RelativeResolution]         FLOAT (53)     NOT NULL,
    [ClassRun1]                  VARCHAR (100)  NULL,
    [Position] INT NOT NULL, 
    CONSTRAINT [PK_ForceResult] PRIMARY KEY CLUSTERED ([SequenceID] ASC, [CalibrationSubTypeId] ASC, [WorkOrderDetailId] ASC)
);

