CREATE TABLE [dbo].[MicroResult] (
    [SequenceID]           INT        NOT NULL,
    [CalibrationSubTypeId] INT        NOT NULL,
    [WorkOrderDetailId]    INT        NOT NULL,
    [NominalValue]         FLOAT (53) NOT NULL,
    [Test1X]               FLOAT (53) NOT NULL,
    [Test1Y]               FLOAT (53) NOT NULL,
    [Test2X]               FLOAT (53) NOT NULL,
    [Test2Y]               FLOAT (53) NOT NULL,
    [Test3X]               FLOAT (53) NOT NULL,
    [Test3Y]               FLOAT (53) NOT NULL,
    [Test4X]               FLOAT (53) NOT NULL,
    [Test4Y]               FLOAT (53) NOT NULL,
    [Test5X]               FLOAT (53) NOT NULL,
    [Test5Y]               FLOAT (53) NOT NULL,
    [Error]                FLOAT (53) NOT NULL,
    [ErrorPer]             FLOAT (53) NOT NULL,
    [Repeateability]       FLOAT (53) NOT NULL,
    [RepeateabilityPer]    FLOAT (53) NOT NULL,
    [Uncertanty]           FLOAT (53) NOT NULL,
    [Standard]             FLOAT (53) NOT NULL,
    [UnBias]               FLOAT (53) NOT NULL,
    [Average]              FLOAT (53) NOT NULL,
    [AveragePer]           FLOAT (53) NOT NULL,
    [Resolution]           FLOAT (53) NOT NULL,
    [DecimalNumber]        INT        NOT NULL,
    [Position]             INT        NOT NULL,
    [Max]                  FLOAT (53) NOT NULL,
    [Min]                  FLOAT (53) NOT NULL,
    CONSTRAINT [PK_MicroResult] PRIMARY KEY CLUSTERED ([SequenceID] ASC, [CalibrationSubTypeId] ASC, [WorkOrderDetailId] ASC),
    CONSTRAINT [FK_MicroResult_Micro_SequenceID_CalibrationSubTypeId_WorkOrderDetailId] FOREIGN KEY ([SequenceID], [CalibrationSubTypeId], [WorkOrderDetailId]) REFERENCES [dbo].[Micro] ([SequenceID], [CalibrationSubTypeId], [WorkOrderDetailId])
);

